<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Laminas\View\Helper\Navigation $nav
 * @var array $options Options provided to the helper, merged with default values.
 *
 * When called from helper breadcrumbs():
 * @var \Laminas\Navigation\Navigation $breadcrumbs
 * @deprecated $crumbs is kept for old themes, not in this partial (see old releases).
 * @var array $crumbs Flat list of crumb, that is an array with "label", "uri", "resource", if any.
 *
 * $nav is currently not available when called from the view helper breadcrumbs.
 */

// Quick hack to insert a span for the last part instead of no tag.
// This span allows a simpler theming and avoit to create a specific partial.
// Furthermore, the nav is wrapped in a main div to simplify global positionning.

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');

$navBreadcrumbs = empty($nav)
    ? $this->navigation()->breadcrumbs($breadcrumbs)
    : $nav->breadcrumbs();

// The separator should be a string, else the default one (" &gt; ") is used.
$separator = ' ' . $options['separator'] . " \n";
$navBreadcrumbs->setSeparator($separator);

// Append a class when there is no uri (for element Structure from module Menu).
// It may be possible to set it invisible too directly in the container.
/** @var \Laminas\Navigation\Page\Uri $navLink */
foreach ($navBreadcrumbs->getContainer()->findAllBy('uri', '') as $navLink) {
    $navLink->setClass('no-link');
}

$navBreadcrumbs->setLinkLast(!empty($options['linkLast']));

// Use (string) instead of render() to manage exception.
$html = (string) $navBreadcrumbs;

// TODO Check if the check is still needed for convert <a> into <span> with aria.
if (empty($options['linkLast']) && $lastLinkPos = mb_strrpos($html, '</a>' . $separator)) {
    $html = mb_substr($html, 0, $lastLinkPos + 4 + mb_strlen($separator)) . '<span class="active" aria-currrent="page">' . mb_substr($html, $lastLinkPos + 4 + mb_strlen($separator)) . '</span>';
}
?>

<div class="breadcrumbs-parent">
    <nav id="breadcrumb" class="breadcrumbs" aria-label="<?= $translate('Breadcrumb') ?>">
        <?= $html ?>
    </nav>
</div>
