<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var string $heading
 * @var array $glossary Array of arrays with "term" and "definition".
 * @var string|null $defaultPerPage
 * @var bool $isHtml
 * @var bool $keepOriginalOrder
 */

// This partial is used by blocks block-glossary and html-glossary.
// The number of elements per page can be set as a theme setting.

$plugins = $this->getHelperPluginManager();
$partial = $plugins->get('partial');
$escape = $plugins->get('escapeHtml');
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');
$escapeAttr = $plugins->get('escapeHtmlAttr');
$themeSetting = $plugins->get('themeSetting');

// $defaultPerPage = (int) $themeSetting('glossary_per_page', 10);

$defaultPerPage = empty($defaultPerPage) ? null : (int) $defaultPerPage;
$isHtml = !empty($isHtml);
$keepOriginalOrder = !empty($keepOriginalOrder);

// There may be multiple start letters.
// TODO Js to manage multiple start letters.
$query = $this->params()->fromQuery();
$currentPage = (int) ($query['page'] ?? 1) ?: 1;
$perPage = (int) ($query['per_page'] ?? 0) ?: $defaultPerPage;
// On the first load, the first letter is the first available one: see below.
// There may be multiple first letters to consolidate small lists.
$startWith = array_filter((array) ($query['startwith'] ?? []), 'strlen');

$hasExtensionIntl = extension_loaded('intl');
$hasExtensionIconv = extension_loaded('iconv');
if ($hasExtensionIntl) $transliterator = \Transliterator::createFromRules(':: NFD; :: [:Nonspacing Mark:] Remove; :: NFC;');

// Create the glossary alphabet, the list of current letters and current definitions and prepare first letters.
$skiplinks = [];
$currents = [];
$currentLetters = [];
foreach ($glossary as $key => $termDefinition) {
    if (($termDefinition['term'] ?? '') === '') {
        unset($glossary[$key]);
        continue;
    }
    $term = (string) $termDefinition['term'];
    $cleanTerm = trim($isHtml ? html_entity_decode(strip_tags($term)) : $term);
    if ($cleanTerm === '') {
        unset($glossary[$key]);
        continue;
    }
    $initial = mb_strtoupper(mb_substr($cleanTerm, 0, 1));
    if ($hasExtensionIntl) {
        $initial = $transliterator->transliterate($initial);
    } elseif ($hasExtensionIconv) {
        $initial = iconv('UTF-8', 'ASCII//TRANSLIT//IGNORE', $initial);
    }
    $skipLink = preg_match('/\W|\d/u', $initial) ? '0-9' : $initial;
    $skiplinks[$skipLink] = true;

    $definition = $termDefinition['definition'] ?? '';
    $glossary[$key] = [
        'term' => $cleanTerm,
        'definition' => $definition,
        'initial' => $initial,
        'skiplink' => $skipLink,
        'html' => $isHtml ? $term : $escape($term),
    ];
}
$glossary = array_values($glossary);

// Order glossary and current definition list by default.
if (!$keepOriginalOrder) {
    if (extension_loaded('intl')) {
        $collator = new \Collator('');
        usort($glossary, function($a, $b) use ($collator) {
            return $collator->compare($a['term'], $b['term']);
        });
    } else {
        usort($glossary, function($a, $b) {
            return strcmp($a['term'], $b['term']);
        });
    }
}

// Add the empty letters.
// Get the default list of initials for latin. To be updated for non-latin references.
// Anyway, even in latin, some characters are not transcoded, like Œ.
$alphabet = ['0-9' => false] + array_fill_keys(range('A', 'Z'), false);
$skiplinks = array_merge($alphabet, $skiplinks);
// Don't display symbols if useless.
if (empty($skiplinks['0-9'])) unset($skiplinks['0-9']);

// Set first letter if not set and prepare the list of currents definitions.
if (empty($startWith) && count($skiplinks)) $startWith = [key(array_filter($skiplinks))];
foreach ($glossary as $key => $termDefinition) {
    if (in_array($termDefinition['initial'], $startWith, true) || in_array($termDefinition['skiplink'], $startWith, true)) {
        $currents[] = $key;
        $currentLetters[] = $termDefinition['skiplink'];
    }
}
$currentLetters = array_unique($currentLetters);

// TODO Use Laminas Paginator?
// Prepare the paginator for the current definition list.
$totalCount = count($currents);
$pageCount = $perPage ? (int) ceil($totalCount / $perPage) : 1;
$currentPage = $currentPage <= 1 ? 1 : $currentPage;
$currentPage = $currentPage >= $pageCount ? $pageCount : $currentPage;
if ($perPage && $pageCount > 1) {
    $offset = ($currentPage - 1) * $perPage;
    $previousPage = $currentPage <= 1 ? null : $currentPage - 1;
    $nextPage = $currentPage >= $pageCount ? null : $currentPage + 1;
    $currents = array_slice($currents, $offset, $perPage);
} else {
    $offset = 0;
    $previousPage = null;
    $nextPage = null;
}

$this->headLink()
    ->appendStylesheet($assetUrl('css/block-plus.css', 'BlockPlus'));
$this->headScript()
    ->appendFile($assetUrl('js/block-plus-glossary.js', 'BlockPlus', 'text/javascript', ['defer' => 'defer']));
?>

<div class="block glossary">
    <?php if (!empty($heading)): ?>
    <h2><?= $escape($heading) ?></h2>
    <?php endif; ?>

    <ul class="glossary-alphabet">
        <?php foreach ($skiplinks as $skiplink => $isSet): ?>
        <li><?= $isSet
            ? sprintf('<a data-skiplink="%s" %shref="#%s">%s</a>', $escapeAttr($skiplink), in_array($skiplink, $currentLetters) ? 'class="current" ' : '', $escapeAttr($skiplink), $escape($skiplink))
            : sprintf('<span class="inactive">%s</span>', $escape($skiplink))
        ?></li>
        <?php endforeach; ?>
    </ul>

    <?php if ($perPage):
        $labelFirst = $escapeAttr($translate('First'));
        $labelNoPrevious = $escapeAttr($translate('No previous'));
        $labelPrevious = $escapeAttr($translate('Previous'));
        $labelNoNext = $escapeAttr($translate('No next'));
        $labelNext = $escapeAttr($translate('Next'));
        $labelLast = $escapeAttr($translate('Last'));
    ?>
    <nav data-per-page="<?= $escapeAttr($perPage) ?>" class="pagination glossary-pagination" role="navigation">
        <a data-page="1" class="pagination-first" href="" title="<?= $labelFirst ?>" aria-label="<?= $labelFirst ?>"></a>
        <?php if ($currentPage <= 1): ?>
        <span class="pagination-previous" title="<?= $labelNoPrevious ?>" aria-label="<?= $labelNoPrevious ?>"></span>
        <?php else: ?>
        <a data-page="<?= $escapeAttr($previousPage) ?>" class="pagination-previous" href="" title="<?= $labelPrevious ?>" aria-label="<?= $labelPrevious ?>"></a>
        <?php endif; ?>
        <form action="">
            <input class="pagination-current" name="page" type="tel" value="<?= $escapeAttr($currentPage) ?>"/>
        </form>
        <span class="pagination-total"><?= $escape($pageCount) ?></span>
        <?php if ($currentPage >= $pageCount): ?>
        <span class="pagination-next" title="<?= $labelNoNext ?>" aria-label="<?= $labelNoNext ?>"></span>
        <?php else: ?>
        <a data-page="<?= $escapeAttr($nextPage) ?>" class="pagination-next" href="" title="<?= $labelNext ?>" aria-label="<?= $labelNext ?>"></a>
        <?php endif; ?>
        <a data-page="<?= $escapeAttr($pageCount) ?>" class="pagination-last" href="" title="<?= $labelLast ?>" aria-label="<?= $labelLast ?>"></a>
    </nav>
    <?php endif; ?>

    <dl class="glossary-items">
        <?php foreach ($glossary as $key => $termDefinition): ?>
        <div class="glossary-item" data-initial="<?= $escapeAttr($termDefinition['initial']) ?>" data-skiplink="<?= $escapeAttr($termDefinition['skiplink']) ?>" <?= in_array($key, $currents) ? '' : ' style="display:none;"' ?>>
            <dt class="glossary-term"><?= $termDefinition['html'] ?></dt>
            <dd class="glossary-definition"><?= $isHtml ? $termDefinition['definition'] : $escape($termDefinition['definition']) ?></dd>
        </div>
        <?php endforeach; ?>
    </dl>

</div>
