<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var array $assets Contains AssetRepresentation, caption, title, url and class.
 * @var string $heading
 */

// Note: this hero uses the classes and js of Twitter Bootstrap.

?>
<?php if ($heading): ?>
<h2><?= $heading ?></h2>
<?php endif; ?>

<?php if ($assets): ?>
<?php // The hero use the first asset. ?>
<?php $asset = reset($assets); ?>
<div class="header-wrapper <? $asset['class'] ?>" style="background-image:url(<?= $asset['asset']->assetUrl() ?>);">
    <?php if ($asset['caption']): ?>
    <div class="container mt-5">
        <div class="row mt-5">
            <div class="col-md-6  offset-3 mt-5">
                <h1 class="lorem text-uppercase text-center text-justify"><?= $asset['caption'] ?></h1>
                <?php if ($asset['title'] && $asset['url']): ?>
                <a href="<?= $asset['url'] ?>"><button class="btn knowmore"><?= $asset['title'] ?></button></a>
                <?php endif; ?>
            </div>
        </div>
    </div>
    <?php endif; ?>
</div>
<?php endif; ?>
