<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var array $attachments Contains keys:
 *   - asset (AssetRepresentation)
 *   - page (PageRepresentation)
 *   - caption (string): the html is purified according to settings
 *   - alt_link_title (string)
 *   Specific to the module version:
 *   - class (string)
 * @var string $heading
 * @var string $className
 *
 * @see \BlockPlus\View\Helper\AssetElement
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$thumbnail = $plugins->get('thumbnail');
$escapeAttr = $plugins->get('escapeHtmlAttr');
// Support assetElement when available, that may not be the case when the module is disabled.
$thumbnail = $plugins->has('assetElement') ? $plugins->get('assetElement') : $plugins->get('thumbnail');

$className ??= '';
?>

<div class="block block-asset assets <?= $escape($className) ?>">
    <?php if (!empty($heading)): ?>
    <h2><?= $escape($heading) ?></h2>
    <?php endif; ?>
    <?php foreach ($attachments as $attachment):
        $assetHtml = $attachment['asset'] ? $thumbnail($attachment['asset'], 'square') : '';
    ?>
    <div class="asset<?= empty($attachment['class']) ? '' : ' ' . $escapeAttr($attachment['class']) ?>">
        <?php if (isset($attachment['page'])): ?>
            <a href="<?= $escapeAttr($attachment['page']->siteUrl()) ?>">
                <?= $assetHtml ?>
                <span class="link-title">
                    <?= $attachment['alt_link_title'] === '' ? $escape($attachment['page']->title()) : $escape($attachment['alt_link_title']) ?>
                </span>
            </a>
        <?php else: ?>
             <?= $assetHtml ?>
        <?php endif; ?>
        <?php if ($attachment['caption'] !== ''): ?>
        <div class="caption">
            <?= empty($attachment['raw']) ? $attachment['caption'] : $escape($attachment['caption']) ?>
        </div>
        <?php endif; ?>
    </div>
    <?php endforeach; ?>
</div>
