<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var array $assets Contains AssetRepresentation and optional url and label.
 * @var string $heading
 * @var string $misc
 */

?>
<style>
.partners {
    text-align: center;
}
.partner-logo img {
    margin: 12px;
    height: 128px;
    max-height: 128px;
    width: auto;
}
</style>
<div class="block-assets partners">
    <?php if ($heading): ?>
    <h2><?= $heading ?></h2>
    <?php endif; ?>

    <div class="asset partners-logos">
    <?php foreach ($assets as $asset): ?>
        <?php if ($asset['url']): ?>
        <a class="partner-logo" href="<?= $asset['url'] ?>"<?php if (filter_var($asset['url'], FILTER_VALIDATE_URL)): ?> target="_blank"<?php endif; ?>>
            <img src="<?= $asset['asset']->assetUrl() ?>" alt="<?= $asset['label'] ?>"/>
        </a>
        <?php else: ?>
        <span class="partner-logo">
            <img src="<?= $asset['asset']->assetUrl() ?>" alt="<?= $asset['label'] ?>"/>
        </span>
        <?php endif; ?>
    <?php endforeach; ?>
    </div>
</div>
