<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var array $attachments Contains keys:
 *   - asset (AssetRepresentation)
 *   - page (PageRepresentation)
 *   - caption (string): the html is purified according to settings
 *   - alt_link_title (string)
 *   Specific to the module version:
 *   - class (string)
 *   - url (string): deprecated, will be removed. Use "page", "caption", alt title, or original asset alt value instead.
 * @var array $assets Deprecated, alias of attachments.
 * @var string $heading
 * @var string $className
 * @var string $alignment
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$escapeAttr = $plugins->get('escapeHtmlAttr');
$assetElement = $plugins->get('assetElement');
?>

<style>
.align-left { float: left; margin-right: 6px; }
.align-right { float: right; margin-left: 6px; }
.clear { clear: both; }
</style>

<div class="block block-asset assets <?= $escape($className . ' ' . $alignment) ?>">
    <?php if (!empty($heading)): ?>
    <h2><?= $escape($heading) ?></h2>
    <?php endif; ?>
    <?php $index = 0; ?>
    <?php foreach ($attachments as $attachment): ?>
    <div class="asset<?= empty($attachment['class']) ? '' : ' ' . $escapeAttr($attachment['class']) ?>">
        <?php if ($attachment['asset']): ?>
            <?php $attachmentUrl = $attachment['page'] ? $attachment['page']->siteUrl() : ($attachment['url'] ?? null); ?>
            <?php if ($attachmentUrl): ?>
        <a class="<?= ++$index % 2 ? 'align-left' : 'align-right' ?>" href="<?= $escapeAttr($attachmentUrl) ?>"<?php if (filter_var($attachmentUrl, FILTER_VALIDATE_URL)): ?> target="_blank"<?php endif; ?>>
            <?= $assetElement($attachment['asset'], ['alt' => $attachment['alt_link_title']]) ?>
        </a>
            <?php else: ?>
        <span class="<?= ++$index % 2 ? 'align-left' : 'align-right' ?>">
            <?= $assetElement($attachment['asset'], ['alt' => $attachment['alt_link_title']]) ?>
        </span>
            <?php endif; ?>
        <?php endif; ?>
        <?php if ($attachment['caption']): ?>
        <div class="caption">
            <?= $attachment['caption'] ?>
        </div>
        <?php endif; ?>
        <div class="clear"></div>
    </div>
    <?php endforeach; ?>
</div>
