<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var array $assets Contains keys "asset" (AssetRepresentation), "caption", "title", "url" and "class".
 * @var string $heading
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$escapeAttr = $plugins->get('escapeHtmlAttr');

$assetElement = $plugins->get('assetElement');
?>

<div class="block block-assets">
    <?php if (!empty($heading)): ?>
    <h2><?= $escape($heading) ?></h2>
    <?php endif; ?>

    <?php foreach ($assets as $asset): ?>
    <div class="asset <?= $escapeAttr($asset['class']) ?>">
        <?php if ($asset['asset']): ?>
            <?php if ($asset['url']): ?>
        <a href="<?= $escapeAttr($asset['url']) ?>"<?php if (filter_var($asset['url'], FILTER_VALIDATE_URL)): ?> target="_blank"<?php endif; ?>>
            <?= $assetElement($asset['asset'], ['alt' => $asset['title']]) ?>
        </a>
            <?php else: ?>
        <span>
            <?= $assetElement($asset['asset'], ['alt' => $asset['title']]) ?>
        </span>
            <?php endif; ?>
        <?php endif; ?>
        <?php if ($asset['caption']): ?>
        <div class="caption">
            <?= $asset['caption'] ?>
        </div>
        <?php endif; ?>
    </div>
    <?php endforeach; ?>
</div>
