<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var array $attachments Contains keys:
 *   - asset (AssetRepresentation)
 *   - page (PageRepresentation)
 *   - caption (string): the html is purified according to settings
 *   - alt_link_title (string)
 *   Specific to the module version:
 *   - class (string)
 *   - url (string): deprecated, will be removed. Use "page", "caption", alt title, or original asset alt value instead.
 * @var array $assets Deprecated, alias of attachments.
 * @var string $heading
 * @var string $className
 */

// Note: this hero uses the classes and js of Twitter Bootstrap.
// The hero uses a random asset.

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$escapeAttr = $plugins->get('escapeHtmlAttr');
?>

<?php if (!empty($heading)): ?>
<h2><?= $escape($heading) ?></h2>
<?php endif; ?>

<?php if (!count($attachments)) return; ?>
<?php $attachment = $attachments[array_rand($attachments)]; ?>
<?php if (empty($attachment['asset'])) return; ?>

<div class="block header-wrapper <?= $escapeAttr($attachment['class']) ?>" style="background-image:url(<?= $attachment['asset']->assetUrl() ?>);">
    <?php if ($attachment['caption']): ?>
    <div class="container mt-5">
        <div class="row mt-5">
            <div class="col-md-6  offset-3 mt-5">
                <h1 class="lorem text-uppercase text-center text-justify"><?= $attachment['caption'] ?></h1>
                <?php $attachmentUrl = $attachment['page'] ? $attachment['page']->siteUrl() : ($attachment['url'] ?? null); ?>
                <?php if ($attachment['alt_link_title'] && $attachmentUrl): ?>
                <a href="<?= $escapeAttr($attachmentUrl) ?>"><button class="btn knowmore"><?= $escape($attachment['alt_link_title']) ?></button></a>
                <?php endif; ?>
            </div>
        </div>
    </div>
    <?php endif; ?>
</div>
