<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var array $assets Contains keys "asset" (AssetRepresentation), "caption", "title", "url" and "class".
 * @var string $heading
 */

// Caption is not used in this template.

?>

<style>
.partners {
    text-align: center;
}
.partner-logo img {
    margin: 12px;
    height: 128px;
    max-height: 128px;
    width: auto;
}
</style>
<div class="block-assets partners">
    <?php if ($heading): ?>
    <h2><?= $heading ?></h2>
    <?php endif; ?>

    <div class="asset partners-logos">
    <?php foreach ($assets as $asset): ?>
        <?php if ($asset['url']): ?>
        <a class="partner-logo <?= $asset['class'] ?>" href="<?= $asset['url'] ?>" target="_blank">
            <img src="<?= $asset['asset']->assetUrl() ?>" alt="<?= $asset['title'] ?>"/>
        </a>
        <?php else: ?>
        <span class="partner-logo <?= $asset['class'] ?>">
            <img src="<?= $asset['asset']->assetUrl() ?>" alt="<?= $asset['title'] ?>"/>
        </span>
        <?php endif; ?>
    <?php endforeach; ?>
    </div>
</div>
