<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SitePageBlockRepresentation $block
 * @var string $params
 * @var string $paramType "auto", "raw", "ini", "json_array", "key_value", "key_value_array".
 * @var string|array $parameters Params according to type.
 *
 * Fill this partial as you want. The view is available, so any feature can be used.
 * Warning: check security of any user input.
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
?>

<div class="block block-simple">
    <?= nl2br(is_array($params) ? $escape(json_encode($params, 448)) : $escape($params)) ?>
</div>
