<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Api\Representation\SitePageRepresentation $page
 * @var \Omeka\Api\Representation\SitePageBlockRepresentation $block
 * @var \Laminas\View\Helper\Navigation $nav
 * @var array $activePage
 * @var bool $prependHome
 * @var bool $appendCurrent
 * @var bool $linkLast
 * @var string $separator
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$siteSetting = $plugins->get('siteSetting');
$isHomePage = $plugins->get('isHomePage')();

$homePage = $isHomePage ? $page : $site->homepage();
$displayOnHomePage = $isHomePage ? (bool) $siteSetting('blockplus_breadcrumbs_homepage') : false;

$nav = $site->publicNav();
$activePage = $nav->findActive($nav->getContainer());
?>

<?php if ($activePage): ?>
    <?php if ($displayOnHomePage || !$isHomePage /* && $activePage['depth'] !== 0 */): ?>
<nav class="breadcrumbs" aria-label="<?= $translate('Breadcrumb') ?>">
    <?= $prependHome && $homePage ? $homePage->link($homePage->title()) . $separator : '' ?>
    <?= $nav->breadcrumbs()->setSeparator($separator)->setLinkLast($linkLast) ?>
</nav>
    <?php endif; ?>
<?php elseif ($prependHome || $appendCurrent): // Isolated page. ?>
<nav class="breadcrumbs" aria-label="<?= $translate('Breadcrumb') ?>">
    <?= $prependHome && $homePage ? $homePage->link($homePage->title()) . ($appendCurrent ? $separator : '') : '' ?>
    <?php if ($appendCurrent): ?>
    <?= $linkLast ? $page->link($page->title()) : '<span>' . $this->escapeHtml($page->title()) . '</span>' ?>
    <?php endif; ?>
</nav>
<?php endif; ?>
