<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Api\Representation\SitePageBlockRepresentation $block
 */

// Same structure than application/view/omeka/site/page/show.
// So does not take care of module breadcrumbs settings, in particular separator.

$nav = $site->publicNav();
$activePage = $nav->findActive($nav->getContainer());
?>

<?php if ($activePage && $activePage['depth'] !== 0): ?>
<nav class="breadcrumbs"><?= $nav->breadcrumbs() ?></nav>
<?php endif; ?>
