<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var string $resourceType
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation[] $resources
 * @var string $heading
 * @var string $linkText
 * @var array $components
 * @var array $query
 * @var array $sortHeadings
 * @var array|false $pagination
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
$thumbnail = $plugins->get('thumbnail');
$siteSetting = $plugins->get('siteSetting');

$showThumbnail = in_array('thumbnail', $components);
$showHeading = in_array('resource-heading', $components);
$showBody = in_array('resource-body', $components);
$headingTerm = $siteSetting('browse_heading_property_term');
$bodyTerm = $siteSetting('browse_body_property_term');

$untitled = $translate('[Untitled]');

$filterLocale = (bool) $siteSetting('filter_locale_values');
$lang = $filterLocale ? $this->lang() : null;
$langValue = $filterLocale ? [$this->lang(), ''] : null;
?>

<div class="block preview-block">

    <?php if (!empty($heading)): ?>
    <h2><?= $escape($heading) ?></h2>
    <?php endif; ?>

    <?php if (!empty($sortHeadings)): ?>
    <div class="browse-controls">
        <?= $this->sortSelector($sortHeadings) ?>
    </div>
    <?php endif; ?>

    <ul class="resource-list preview">
    <?php
    foreach ($resources as $resource):
        if ($showHeading) {
            $heading = $headingTerm ? $resource->value($headingTerm, ['lang' => $langValue]) : null;
            $heading = $heading ? $heading->asHtml() : $escape($resource->displayTitle($untitled, $lang));
        } else {
            $heading = '';
        }
        if ($showBody) {
            $body = $bodyTerm ? $resource->value($bodyTerm, ['lang' => $langValue]) : null;
            $body = $body ? $body->asHtml() : $escape($resource->displayDescription(null, $lang));
        } else {
            $body = '';
        }
        $thumb = $showThumbnail ? $thumbnail($resource, 'medium', ['title' => $heading]) : null;
        ?>
        <li class="<?= $resourceType ?> resource">
            <?php if ($thumb): ?>
            <?= $resource->linkRaw($thumb) ?>
            <?php endif; ?>
            <?php if ($showHeading && $heading): ?>
            <h4><?= $resource->linkRaw($heading) ?></h4>
            <?php endif; ?>
            <?php if ($showBody && $body): ?>
            <div class="description"><?= $body ?></div>
            <?php endif; ?>
        </li>
    <?php endforeach; ?>
    </ul>

    <?php
    if (!empty($pagination)):
        echo $this->pagination();
    endif;
    ?>

    <?php if ($linkText): ?>
        <?= $this->hyperlink($linkText, $this->url(
            'site/resource', ['controller' => $resourceType, 'action' => 'browse', 'site-slug' => $site->slug()], ['query' => $query], true
        )) ?>
    <?php endif; ?>

</div>
