<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SitePageBlockRepresentation $block
 * @var string $heading
 * @var array $embeds
 * @var string $html
 * @var string $showTitleOption
 * @var string $captionPosition
 * @var string $linkText
 * @var string $linkUrl
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$escapeAttr = $plugins->get('escapeHtmlAttr');
$hyperlink = $plugins->get('hyperlink');
?>

<div class="block external-content media-text">
    <?php if (!empty($heading)): ?>
    <h2><?= $escape($heading) ?></h2>
    <?php endif; ?>

<div class="<?= ' captions-' . $captionPosition ?> media file">
    <div class="embeds attachments">
<?php foreach ($embeds as $embed): ?>
    <div class="item resource">
    <?php
    $data = $embed['data'];
    if ($data):
        if ($data['type'] == 'photo'):
            $url = $data['url'];
            $width = $data['width'];
            $height = $data['height'];
            $title = empty($data['title']) ? $url : $data['title'];
            echo sprintf(
                '<img loading="lazy" src="%s" width="%s" height="%s" alt="%s">',
                $escapeAttr($url),
                $escapeAttr($width),
                $escapeAttr($height),
                $escapeAttr($title)
            );
        elseif (!empty($data['html'])):
            echo $data['html'];
        else:
            $showTitleOption = 'title';
        endif;

        if ($showTitleOption === 'title'):
            $source = $embed['source'];
            $title = empty($data['title']) ? $source : $data['title'];
        ?>
        <h3><?= $hyperlink($title, $source) ?></h3>
        <?php endif; ?>
    <?php endif; ?>

    <?php $caption = $data['caption'] ?? null; ?>
    <?php if ($caption): ?>
        <div class="caption">
            <?= $caption ?>
        </div>
    <?php endif; ?>
    </div>
<?php endforeach; ?>
    </div>
</div>
<?= $html ?>

<?php if ($linkText && $linkUrl): ?>
<?= $hyperlink($linkText, $linkUrl) ?>
<?php elseif ($linkText): ?>
<span><?= $escape($linkText) ?></span>
<?php endif; ?>
</div>
