<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SitePageBlockRepresentation $block
 * @var \Omeka\Api\Representation\SiteBlockAttachmentRepresentation[] $attachments
 * @var string $thumbnailType
 * @var string $showTitleOption
 * @var string $heading
 */

$thumbnail = $this->plugin('thumbnail');
?>

<div class="item-showcase">
    <?php if (!empty($heading)): ?>
    <h2><?= $heading ?></h2>
    <?php endif; ?>

<?php foreach ($attachments as $attachment): ?>
    <div class="item resource">
    <?php $item = $attachment->item(); ?>
    <?php if ($item): ?>
        <?php
        $media = $attachment->media() ?: $item->primaryMedia();
        if ($media):
            echo $item->linkRaw($thumbnail($media, $thumbnailType));
        endif;
        ?>
        <?php if ($showTitleOption === 'item_title'): ?>
        <h3><?= $item->link($item->displayTitle()) ?></h3>
        <?php elseif ($showTitleOption === 'file_name'): ?>
        <h3><?= $media->displayTitle() ?></h3>
        <?php endif; ?>
    <?php endif; ?>

    <?php $caption = $attachment->caption(); ?>
    <?php if ($caption): ?>
        <div class="caption"><?= $caption ?></div>
    <?php endif; ?>
    </div>
<?php endforeach; ?>
</div>
