<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SitePageBlockRepresentation $block
 * @var \Omeka\Api\Representation\SiteBlockAttachmentRepresentation[] $attachments
 * @var string $thumbnailType
 * @var string $showTitleOption
 */

$plugins = $this->getHelperPluginManager();
$siteLang = $plugins->get('lang')();
$hyperlink = $plugins->get('hyperlink');
$thumbnail = $plugins->get('thumbnail');
$siteSetting = $plugins->get('siteSetting');

$linkType = $siteSetting('attachment_link_type', 'item');

$filterLocale = (bool) $siteSetting('filter_locale_values');
$lang = $filterLocale ? $siteLang : null;
?>

<div class="block item-showcase">
    <?php
    foreach ($attachments as $attachment):
        $render = null;
        $title = null;
        $link = null;
        $item = $attachment->item();
        $media = null;
        if ($item):
            $media = $attachment->media() ?: $item->primaryMedia();
            if ($media):
                $render = $item->linkRaw($thumbnail($media, $thumbnailType));
            endif;

            if ($showTitleOption === 'item_title'):
                $title = $item->displayTitle(null, $lang);
            elseif ($media && $showTitleOption == 'file_name'):
                $title = $media->displayTitle(null, $lang);
            endif;

            if ($title):
                if ($media && $linkType === 'media'):
                    $link = $media->link($title);
                elseif ($media && $linkType === 'original' && $media->hasOriginal()):
                    $link = $hyperlink($title, $media->originalUrl());
                else:
                    $link = $item->link($title);
                endif;
            endif;
        endif;

        $caption = $attachment->caption();
    ?>
    <div class="item resource">
        <?= $render ?>
        <?php if ($link): ?>
        <h3><?= $link ?></h3>
        <?php endif; ?>
        <?php if ($caption): ?>
        <div class="caption">
            <?= $caption ?>
        </div>
        <?php endif; ?>
    </div>
<?php endforeach; ?>
</div>
