<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SitePageBlockRepresentation $block
 * @var \Omeka\Api\Representation\SiteBlockAttachmentRepresentation[] $attachments
 * @var string $thumbnailType
 * @var string $showTitleOption
 * @var string $heading
 */

$plugins = $this->getHelperPluginManager();
$thumbnail = $plugins->get('thumbnail');
$hyperlink = $plugins->get('hyperlink');
$siteSetting = $plugins->get('siteSetting');

$linkType = $siteSetting('attachment_link_type', 'item');
?>

<div class="block item-showcase">
    <?php if (!empty($heading)): ?>
    <h2><?= $heading ?></h2>
    <?php endif; ?>

    <?php
    foreach ($attachments as $attachment):
        $render = null;
        $title = null;
        $link = null;
        $item = $attachment->item();
        if ($item):
            $media = $attachment->media() ?: $item->primaryMedia();
            if ($media):
                $render = $item->linkRaw($thumbnail($media, $thumbnailType));
            endif;

            if ($showTitleOption == 'item_title'):
                $title = $item->displayTitle();
            elseif ($media && $showTitleOption == 'file_name'):
                $title = $media->displayTitle();
            endif;

            if ($title):
                if ($media && $linkType === 'media'):
                    $link = $media->link($title);
                elseif ($media && $linkType === 'original' && $media->hasOriginal()):
                    $link = $hyperlink($title, $media->originalUrl());
                else:
                    $link = $item->link($title);
                endif;
            endif;
        endif;

        $caption = $attachment->caption();
    ?>
    <div class="item resource">
        <?= $render ?>
        <?= $link ?>
        <?php if ($caption): ?>
        <div class="caption">
            <?= $caption ?>
        </div>
        <?php endif; ?>
    </div>
<?php endforeach; ?>
</div>
