<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SitePageBlockRepresentation $block
 * @var \Omeka\Api\Representation\ItemSetRepresentation[] $itemSets
 * @var string $thumbnailType
 * @var string $showTitleOption
 * @var string $heading
 */

// Use hyperlink to allow to get resource url from api: method $resource->url() does not work for api.

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$hyperlink = $plugins->get('hyperlink');
$thumbnail = $plugins->get('thumbnail');

$defaultThumbnail = $this->assetUrl('thumbnails/default.png', 'Omeka', true);
$defaultThumbnail = '<img src="' . $defaultThumbnail . '"/>';

$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $filterLocale ? $this->lang() : null;
?>

<div class="block item-set-showcase">
    <?php if (!empty($heading)): ?>
    <h2><?= $escape($heading) ?></h2>
    <?php endif; ?>
    <?php
    foreach ($itemSets as $itemSet):
        $render = null;
        $title = null;
        $link = null;

        $itemSetThumbnail = $thumbnail($itemSet, $thumbnailType) ?: $defaultThumbnail;
        $render = $hyperlink->raw($itemSetThumbnail, $itemSet->siteurl());

        if ($showTitleOption !== 'no_title'):
            $title = $itemSet->displayTitle(null, $lang);
            $link = $hyperlink($title, $itemSet->siteurl());
        endif;
    ?>
    <div class="item-set resource">
        <?= $render ?>
        <?= $link ?>
        <div class="caption">
            <?= $itemSet->displayDescription(null, $lang) ?>
        </div>
    </div>
    <?php endforeach; ?>
</div>
