<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var array $links
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$escapeAttr = $plugins->get('escapeHtmlAttr');
?>

<div class="block links">
    <ul class="list-links">
    <?php foreach ($links as $url => $label):
        [$label, $description] = array_map('trim', explode('=', $label, 2)) + ['', ''];
    ?>
        <li>
            <a href="<?= $escapeAttr($url) ?>"<?php if (filter_var($url, FILTER_VALIDATE_URL)): ?> target="_blank" rel="noopener"<?php endif; ?>><?= $escape($label) ?></a>
            <?php if ($description):?>
            <p><?= $escape($description) ?></p>
            <?php endif; ?>
        </li>
    <?php endforeach; ?>
    </ul>
</div>
