<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation[] $sites
 * @var \Omeka\Api\Representation\SiteRepresentation $currentSite
 * @var bool $pagination
 * @var bool $summaries
 * @var bool $thumbnails
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$partial = $plugins->get('partial');
?>

<div class="block list-of-sites">
    <div class="site-list">
        <?php
        foreach ($sites as $site):
            echo $partial('common/site-list-entry', ['site' => $site, 'showSummary' => $summaries, 'showThumbnail' => $thumbnails]);
        endforeach;
        ?>
    </div>
    <?php
    if ($pagination):
        echo $this->pagination();
    endif;
    ?>
</div>
