<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation[] $sites
 * @var \Omeka\Api\Representation\SiteRepresentation $currentSite
 * @var string $heading
 * @var bool $pagination
 * @var bool $summaries
 */

$escape = $this->plugin('escapeHtml');
$partial = $this->plugin('partial');
?>

<div class="block list-of-sites">
    <?php if (!empty($heading)): ?>
    <h2><?= $escape($heading) ?></h2>
    <?php endif; ?>

    <div class="site-list">
        <?php
        foreach($sites as $site):
            echo $partial('common/site-list-entry', ['site' => $site, 'showSummary' => $summaries]);
        endforeach;
        ?>
    </div>
    <?php
    if ($pagination):
        echo $this->pagination();
    endif;
    ?>
</div>
