<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SitePageBlockRepresentation $block
 * @var \Omeka\Api\Representation\SiteBlockAttachmentRepresentation[] $attachments
 * @var string $heading
 * @var string $html
 * @var string $alignmentClass
 * @var string $thumbnailType
 * @var string $showTitleOption
 * @var string $captionPosition
 * @var string $link
 */

?>
<div class="media-text">
    <?php if ($heading): ?>
    <h2><?= $heading ?></h2>
    <?php endif; ?>

<div class="<?= $alignmentClass . ' ' . $thumbnailType . ' captions-' . $captionPosition ?> media file">
    <div class="attachments">
<?php foreach($attachments as $attachment): ?>
    <div class="item resource">
    <?php
    $item = $attachment->item();
    if ($item):
    ?>
        <?php
        $media = $attachment->media() ?: $item->primaryMedia();
        if ($media):
            echo $media->render([
                'thumbnailType' => $thumbnailType,
                'link' => $link,
            ]);
        endif;
        ?>
        <?php if ($showTitleOption == 'item_title'): ?>
        <h3><?= $item->link($item->displayTitle()) ?></h3>
        <?php elseif ($showTitleOption == 'file_name'): ?>
        <h3><?= $media->displayTitle() ?></h3>
        <?php endif; ?>
    <?php endif; ?>

    <?php
    $caption = $attachment->caption();
    if ($caption):
    ?>
        <div class="caption"><?= $caption ?></div>
    <?php endif; ?>
    </div>
<?php endforeach; ?>
    </div>
</div>
<?= $html ?>
</div>
