<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Api\Representation\SitePageBlockRepresentation $block
 * @var array $entries Array with keys:
 *   - entry (string): the raw row
 *   - resource: a resource (item, item set, media, page, null)
 *   - resource_name (string): Api name
 *   - resource_type (string): Controller or class name
 *   - site (SiteRepresentation): When the link use another site
 *   - render (html): the link with the thumbnail and title or the media rendering
 *     according to the options
 *   - title (string)
 *   - url (string)
 *   - link_class (string)
 *   - caption (html)
 *   - body (html)
 *   - data (array) For external url
 * @var string $thumbnailType May be original, large, medium or square.
 * @var string $linkType May be original, item or media (site setting)
 * @var string $link Alias of $linkType for compatibility.
 * @var string $showTitleOption May be item_title, file_name or no_title.
 * @var array $classes A list of classes according to entry and options.
 * @var string $mediaDisplay May be thumbnail or embed (default when empty).
 * @var string $layout Option of the form that may be horizontal or vertical (default), included in $classes.
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$hyperlink = $plugins->get('hyperlink');
$escapeAttr = $plugins->get('escapeHtmlAttr');
// May be used to display a metadata or an html of another block of the group.
// $blockMetadata = $plugins->get('blockMetadata');
// $blockGroupData = $plugins->get('blockGroupData');
?>

<div class="block-showcase entries <?= $escapeAttr(implode(' ', $classes)) ?>">
    <?php foreach ($entries as $entry):
        if (empty($entry['entry'])) continue;
        ?>
    <div class="entry entry-<?= $entry['resource_type'] ?> item resource">
        <?= $entry['render'] ?>
        <?php if ($showTitleOption !== 'no_title'): ?>
        <h3>
            <?php if ($entry['title'] && $entry['url']): ?>
            <?= $hyperlink($entry['title'], $entry['url'], ['class' => $entry['link_class']]) ?>
            <?php elseif ($entry['title']): ?>
            <?= $escape($entry['title']) ?>
            <?php endif; ?>
        </h3>
        <?php endif; ?>
        <?php if ($entry['caption']): ?>
        <div class="caption"><?= $entry['caption'] ?></div>
        <?php endif; ?>
        <?php if ($entry['body']): ?>
        <div class="body"><?= $entry['body'] ?></div>
        <?php endif; ?>
    </div>
    <?php endforeach; ?>
</div>
