<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SitePageBlockRepresentation $block
 * @var int $root
 * @var string $term
 * @var string $resource
 * @var int $expanded
 */

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$api = $plugins->get('api');
$escape = $plugins->get('escapeHtml');
$escapeAttr = $plugins->get('escapeHtmlAttr');

// Avoid infinite loop.
$maxLevel = 20;
// Allow to get url quickly.
$tempPlaceholder = '00999999990999999001';
$url = strtr($url('site/resource-id', ['controller' => 'controller', 'action' => 'show', 'id' => $tempPlaceholder], true), ['controller' => '{controller}', $tempPlaceholder => '{reference}']);
$resourceNames = [
    'items' => 'item',
    'item_sets' => 'item-set',
    'media' => 'media',
];

$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $filterLocale ? $this->lang() : null;

$treeMenu = function ($resource, $level = 0) use (&$treeMenu, $term, $api, $escape, $escapeAttr, $expanded, $maxLevel, $url, $resourceNames, $lang) {
    if (!$resource || $level > $maxLevel):
        return;
    endif;

    $title = $resource->displayTitle(null, $lang);

    // Omeka doesn't allow to search multiple type once ('resource', 'resource:item', 'resource:media', 'resource:itemset').
    $children = $resource->value($term, ['all' => true]) ?: [];
    foreach ($children as $key => $child):
        if (substr($child->type(), 0, 8) !== 'resource'):
            unset($children[$key]);
        endif;
    endforeach;
    ?>
    <li class="nav-item has-treeview<?php if ($level < $expanded): ?> menu-open<?php endif; ?>">
        <i class="nav-icon fas <?= $children ? 'fa-plus' : 'fa-minus' ?>"></i>
        <a href="<?= $escapeAttr(strtr($url, ['{controller}' => $resourceNames[$resource->resourceName()], '{reference}' => $resource->id()])) ?>" class="nav-link">
            <span class="ml-2"><?= $escape($title) ?></span>
        </a>
        <ul class="nav nav-treeview"<?php if ($level >= $expanded): ?> style="display: none;"<?php endif; ?>>
            <?php
            foreach ($children as $child):
                $treeMenu($child->valueResource(), $level + 1);
            endforeach;
            ?>
        </ul>
    </li>
    <?php
}
?>

<style>
    .block-tree-structure ul {
        list-style: none;
    }
</style>

<div class="block block-tree-structure">
    <?php $current = $api->read('resources', ['id' => $root])->getContent(); ?>
    <?php if ($current): ?>
    <ul class="nav flex-column treeview mb-3">
    <?= $treeMenu($current, 0, $expanded) ?>
    </ul>
    <?php endif; ?>
</div>
