<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SitePageBlockRepresentation $block
 * @var array $account
 * @var array $messages
 */

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$hyperlink = $this->plugin('hyperlink');
?>

<div class="block block-twitter">
    <?php if (!count($messages)): ?>
    <p><?= $translate('No message.') ?></p>
    <?php else: ?>
    <ul class="messages">
    <?php foreach ($messages as $message): ?>
        <li data-id="<?= $message['id'] ?>">
            <h4><?= $hyperlink->raw('<span>@</span>' . $account['fullname'], $account['url'], ['rel' => 'nofollow noopener', 'target' => '_blank']) ?></h4>
            <div class="message"><?= $message['content'] ?></div>
        </li>
    <?php endforeach; ?>
    </ul>
    <?php endif; ?>
</div>
