<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SitePageBlockRepresentation $block
 * @var array $account
 * @var array $messages
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');
$escapeAttr = $plugins->get('escapeHtmlAttr');
?>

<div class="block block-twitter">
    <?php if (!count($messages)): ?>
    <p><?= $translate('No message.') ?></p>
    <?php else: ?>
    <ul class="messages">
    <?php foreach ($messages as $message): ?>
        <li data-id="<?= $escapeAttr($message['id']) ?>">
            <h4><?= $hyperlink->raw('<span>@</span>' . $account['fullname'], $account['url'], ['rel' => 'nofollow noopener', 'target' => '_blank']) ?></h4>
            <div class="message"><?= $message['content'] ?></div>
        </li>
    <?php endforeach; ?>
    </ul>
    <?php endif; ?>
</div>
