<?php
/**
 * Adaptation of Omeka application/view/common/asset-block-form.phtml
 *
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var array $block
 * @var int $siteId
 * @var string $apiUrl
 * @var array $attachments Warning: not attachments, but array of data
 * @var string $alignmentClassSelect
 * Added:
 * @var \Laminas\Form\Fieldset $fieldset
 */

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');
$formRow = $plugins->get('formRow');
$thumbnail = $plugins->get('thumbnail');
$escapeAttr = $plugins->get('escapeHtmlAttr');

$strings = [];
$strings['openAssetOptions'] = $hyperlink('', '#', ['class' => 'asset-options-configure o-icon-configure button', 'title' => $translate('Open asset options'), 'aria-label' => $translate('Open asset options')]); // @translate
$strings['deleteAttachment'] = $hyperlink('', '#', ['class' => 'o-icon-delete button', 'title' => $translate('Delete attachment'), 'aria-label' => $translate('Delete attachment')]); // @translate
$strings['restoreAttachment'] = $hyperlink('', '#', ['class' => 'o-icon-undo button', 'title' => $translate('Restore attachment'), 'aria-label' => $translate('Restore attachment')]); // @translate
$strings['collapse'] = $translate('Collapse'); // @translate
$strings['assets'] = $translate('Assets'); // @translate
$strings['urlSidebarSelect'] = $escape($url('admin/default', ['controller' => 'asset', 'action' => 'sidebar-select']));
$strings['addAsset'] = $translate('Add asset'); // @translate
$strings['options'] = $translate('Options'); // @translate
$strings['noAssetSelected'] = $translate('No asset selected'); // @translate

$attachmentRowTemplate = <<<HTML
 <div class="attachment%s">
    <span class="sortable-handle"></span>
    <div class="asset-title">
        <div class="thumbnail">%s</div>
        %s
    </div>
    <ul class="actions">
        <li>{$strings['openAssetOptions']}</li>
        <li class="delete">{$strings['deleteAttachment']}</li>
        <li class="undo">{$strings['restoreAttachment']}</li>
    </ul>
    <input type="hidden" class="asset-option asset-page-id" name="o:block[__blockIndex__][o:data][__attachmentIndex__][page]" data-page-title="%s" data-page-url="%s" %s value="%s"/>
    <input type="hidden" class="asset-option asset" name="o:block[__blockIndex__][o:data][__attachmentIndex__][id]" %s value="%s"/>
    <input type="hidden" class="asset-option alternative-link-title" name="o:block[__blockIndex__][o:data][__attachmentIndex__][alt_link_title]" %s value="%s"/>
    <input type="hidden" class="asset-option asset-caption" name="o:block[__blockIndex__][o:data][__attachmentIndex__][caption]" %s value="%s"/>
    <input type="hidden" class="asset-option asset-class" name="o:block[__blockIndex__][o:data][__attachmentIndex__][class]" %s value="%s"/>
</div>
HTML;

$strings['attachmentRowTemplateDefault'] = sprintf($attachmentRowTemplate, ' new', '', '', '', '', 'disabled', '', 'disabled', '', 'disabled', '', 'disabled', '', 'disabled', '');
?>

<style>
    .collapse + .collapsible { overflow: visible; }
</style>
<div class="asset-attachments-form" data-site-id="<?= $siteId ?>" data-page-api-url="<?= $escape($apiUrl) ?>">
    <a href="#" class="collapse" title="<?= $escapeAttr($translate('Collapse')) ?>" aria-label="<?= $escapeAttr($strings['collapse']) ?>"><h4><?= $escapeAttr($strings['assets']) ?></h4></a>
    <div class="attachments collapsible" data-template="<?= $escapeAttr($strings['attachmentRowTemplateDefault']) ?>">
        <?php if ($block):
        foreach($attachments as $attachment):
            echo sprintf(
                $attachmentRowTemplate,
                '',
                $attachment['asset'] ? $thumbnail($attachment['asset'], 'square') : '',
                $attachment['asset'] ? $escape($attachment['asset']->name()) : $escape($strings['noAssetSelected']),
                $attachment['page'] ? $escape($attachment['page']->title()) : '',
                $attachment['page'] ? $escape($attachment['page']->siteUrl()) : '',
                '',
                $attachment['page'] ? $escape($attachment['page']->id()) : '',
                '',
                $attachment['asset'] ? $attachment['asset']->id() : '',
                // Unlike upstream, the title is saved in any case.
                '',
                $escape($attachment['alt_link_title']),
                '',
                $escape($attachment['caption']),
                // Managed via js.
                '',
                empty($attachment['class']) ? '' : $escape($attachment['class']),
            ) . PHP_EOL;
        endforeach;
        endif; ?>
        <button type="button" class="add-asset-attachment" data-sidebar-content-url="<?= $escapeAttr($strings['urlSidebarSelect']) ?>"><?= $escape($strings['addAsset']) ?></button>
    </div>
</div>
<a class="collapse" href="#" title="<?= $escapeAttr($strings['collapse']) ?>" aria-label="<?= $escapeAttr($strings['collapse']) ?>">
    <h4><?= $escape($strings['options']) ?></h4>
</a>
<div class="collapsible">
    <?= $formRow($fieldset->get('o:block[__blockIndex__][o:data][heading]')) ?>
    <?= $formRow($fieldset->get('o:block[__blockIndex__][o:data][className]')) ?>
    <?= $formRow($fieldset->get('o:block[__blockIndex__][o:data][alignment]')) ?>
    <?= $formRow($fieldset->get('o:block[__blockIndex__][o:data][template]')) ?>
    <?php // Inputs "class" and "url" are managed by js because other blocks don't need them. ?>
</div>
