<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var array $attachments Contains keys:
 *   - asset (AssetRepresentation)
 *   - page (PageRepresentation)
 *   - caption (string): the html is purified according to settings
 *   - alt_link_title (string)
 *
 * The optional class and url may be set at start of each caption like:
 * ```
 * url = https://example.org/
 * class = xxx yyy
 * Next lines are the true caption.
 * ```
 *
 * The caption may be an html one.
 * @see \BlockPlus\View\Helper\AssetElement
 */

// Note: this hero uses the classes and js of Twitter Bootstrap.
// The hero uses a random asset.

if (!count($attachments)) return;
$attachment = $attachments[array_rand($attachments)];
if (empty($attachment['asset'])) return;

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$thumbnail = $plugins->get('thumbnail');
$escapeAttr = $plugins->get('escapeHtmlAttr');

// Manage display when the module is disabled.
$thumbnail = $plugins->has('assetElement') ? $plugins->get('assetElement') : $plugins->get('thumbnail');
$captionClassAndUrl = $plugins->get('captionClassAndUrl') ? $plugins->get('captionClassAndUrl') : fn($string) => [trim((string) $string), '', '', $string !== strip_tags($string)];

$asset = $attachment['asset'];
$page = $attachment['page'] ?? null;
$caption = trim($attachment['caption'] ?? '');
if (strlen($caption)) {
    [$caption, $class, $url, $isHtmlCaption] = $captionClassAndUrl($caption);
} else {
    $class = '';
    $url = '';
}
?>

<div class="block header-wrapper<?= strlen($class) ? ' ' . $escapeAttr($class) : '' ?>" style="background-image:url(<?= $asset->assetUrl() ?>);">
    <?php if (strlen($caption)): ?>
    <div class="container mt-5">
        <div class="row mt-5">
            <div class="col-md-6  offset-3 mt-5">
                <h1 class="lorem text-uppercase text-center text-justify"><?= $caption ?></h1>
                <?php $attachmentUrl = $page ? $page->siteUrl() : $url; ?>
                <?php if ($attachment['alt_link_title'] && $attachmentUrl): ?>
                <a href="<?= $escapeAttr($attachmentUrl) ?>"<?php if (filter_var($attachmentUrl, FILTER_VALIDATE_URL)): ?> target="_blank" rel="noopener"<?php endif; ?>>
                    <button class="btn knowmore"><?= $escape($attachment['alt_link_title']) ?></button>
                </a>
                <?php endif; ?>
            </div>
        </div>
    </div>
    <?php endif; ?>
</div>
