<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var array $attachments Contains keys:
 *   - asset (AssetRepresentation)
 *   - page (PageRepresentation)
 *   - caption (string): the html is purified according to settings
 *   - alt_link_title (string)
 *
 * Removed during migration to Omeka S block Asset and not managed for now:
 *   - class (string)
 *   - url (string): deprecated, will be removed. Use "page", "caption", alt title,
 *     or original asset alt value instead. For now, use first part of "class"
 */

// This template is the equivalent of the old "assets.phtml" one, before upstream merge.

// The url may be stored in class.
$matches = [];
foreach ($attachments as $attachment) {
    $attachment['url'] = '';
    $class = $attachment['class'] ?? '';
    if (strpos($class, '/') !== false) {
        preg_match('~(?<url>(?:https?:/)?/\S+)~', $class, $matches);
        $attachment['url'] = $matches['url'];
        $attachment['class'] = str_replace($matches['url'], '', $class);
    }
}

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$thumbnail = $plugins->get('thumbnail');
$escapeAttr = $plugins->get('escapeHtmlAttr');
// Support assetElement when available, that may not be the case when the module is disabled.
$thumbnail = $plugins->has('assetElement') ? $plugins->get('assetElement') : $plugins->get('thumbnail');
?>

<div class="block block-asset assets">
    <?php foreach ($attachments as $attachment):
        $assetHtml = $attachment['asset'] ? $thumbnail($attachment['asset'], 'square') : '';
    ?>
    <div class="asset<?= empty($attachment['class']) ? '' : ' ' . $escapeAttr($attachment['class']) ?>">
        <?php if (isset($attachment['page'])): ?>
            <a href="<?= $escapeAttr($attachment['page']->siteUrl()) ?>">
                <?= $assetHtml ?>
                <span class="link-title">
                    <?= $attachment['alt_link_title'] === '' ? $escape($attachment['page']->title()) : $escape($attachment['alt_link_title']) ?>
                </span>
            </a>
        <?php elseif (isset($attachment['url'])): ?>
            <a href="<?= $escapeAttr($attachment['url']) ?>"<?php if (filter_var($attachment['url'], FILTER_VALIDATE_URL)): ?> target="_blank" rel="noopener"<?php endif; ?>>
                <?= $assetHtml ?>
                <span class="link-title">
                    <?= $attachment['alt_link_title'] === '' ? $escape($attachment['page']->title()) : $escape($attachment['alt_link_title']) ?>
                </span>
            </a>
        <?php else: ?>
             <?= $assetHtml ?>
        <?php endif; ?>
        <?php if ($attachment['caption'] !== ''): ?>
        <div class="caption">
            <?= empty($attachment['raw']) ? $attachment['caption'] : $escape($attachment['caption']) ?>
        </div>
        <?php endif; ?>
    </div>
    <?php endforeach; ?>
</div>
