<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var array $attachments Contains keys:
 *   - asset (AssetRepresentation)
 *   - page (PageRepresentation)
 *   - caption (string): the html is purified according to settings
 *   - alt_link_title (string)
 *
 * The optional class and url may be set at start of each caption like:
 * ```
 * url = https://example.org/
 * class = xxx yyy
 * Next lines are the true caption.
 * ```
 *
 * The caption may be an html one.
 *
 * @see \BlockPlus\View\Helper\AssetElement
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$thumbnail = $plugins->get('thumbnail');
$escapeAttr = $plugins->get('escapeHtmlAttr');

// Manage display when the module is disabled.
$thumbnail = $plugins->has('assetElement') ? $plugins->get('assetElement') : $plugins->get('thumbnail');
$captionClassAndUrl = $plugins->get('captionClassAndUrl') ? $plugins->get('captionClassAndUrl') : fn($string) => [$string, '', '', $string !== strip_tags($string)];
?>

<style>
.partners {
    text-align: center;
}
.partner-logo img {
    margin: 12px;
    height: 128px;
    max-height: 128px;
    width: auto;
}
</style>

<div class="partners assets">
    <div class="asset partners-logos">
    <?php foreach ($attachments as $attachment):
        if (!$attachment['asset']) continue;
        $asset = $attachment['asset'];
        $assetImage = $thumbnail($asset, 'square');
        $page = $attachment['page'] ?? null;
        $caption = trim($attachment['caption'] ?? '');
        if (strlen($caption)) {
            [$caption, $class, $url, $isHtmlCaption] = $captionClassAndUrl($caption);
        } else {
            $class = '';
            $url = '';
        }
        ?>
        <?php $attachmentUrl = $page ? $page->siteUrl() : $url ?>
        <?php if ($attachmentUrl): ?>
        <a class="partner-logo<?= strlen($class) ? ' ' . $escapeAttr($class) : '' ?>" href="<?= $escapeAttr($attachmentUrl) ?>"<?php if (filter_var($attachmentUrl, FILTER_VALIDATE_URL)): ?> target="_blank" rel="noopener"<?php endif; ?>>
            <img loading="lazy" src="<?= $asset->assetUrl() ?>" alt="<?= empty($attachment['alt_link_title']) ? '' : $escapeAttr($attachment['alt_link_title']) ?>"/>
        </a>
        <?php else: ?>
        <span class="partner-logo<?= strlen($class) ? ' ' . $escapeAttr($class) : '' ?>">
            <img loading="lazy" src="<?= $asset->assetUrl() ?>" alt="<?= empty($attachment['alt_link_title']) ? '' : $escapeAttr($attachment['alt_link_title']) ?>"/>
        </span>
        <?php endif; ?>
    <?php endforeach; ?>
    </div>
</div>
