<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SitePageBlockRepresentation $block
 * @var string $params
 * @var string $paramType "auto", "raw", "ini", "json_array", "key_value", "key_value_array".
 * @var string|array $parameters Params according to type.
 *
 * Fill this partial as you want. The view is available, so any feature can be used.
 * Warning: check security of any user input.
 */

$htmlPurifier = $block->getServiceLocator()->get('Omeka\HtmlPurifier');
$html = $htmlPurifier->purify($params);
?>

<div class="block block-simple block-simple-html">
    <?= $html ?>
</div>
