<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Api\Representation\SitePageRepresentation $page
 * @var \Omeka\Api\Representation\SitePageBlockRepresentation $block
 * @var \Laminas\View\Helper\Navigation $nav
 * @var array $activePage
 * @var bool $prependHome
 * @var bool $appendCurrent
 * @var bool $linkLast
 * @var string $separator
 */

// Same structure than application/view/omeka/site/page/show.
// So does not take care of module breadcrumbs settings, in particular separator.

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');

$nav = $site->publicNav();
$activePage = $nav->findActive($nav->getContainer());
?>

<?php if ($activePage && $activePage['depth'] !== 0): ?>
<nav class="breadcrumbs" aria-label="<?= $translate('Breadcrumb') ?>"><?= $nav->breadcrumbs() ?></nav>
<?php endif; ?>
