<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SitePageBlockRepresentation $block
 * @var string $resourceType
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation[] $resources
 * @var string $heading
 * @var string $linkText
 * @var array $components
 * @var array $query
 *
 * Moved during migration to Omeka S as deprecated block layout data.
 * Normally, they are not used and should be removed.
 * When needed, it is recommended to use block Search results instead.
 * @var array $sortHeadings
 * @var array|false $pagination
 * @var string $resourceTemplate
 */

// This template is kept for compatibiliy with old block and should be replaced
// by the default one.

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');
$thumbnail = $plugins->get('thumbnail');
$siteSetting = $plugins->get('siteSetting');
$escapeValueOrGetHtml = $plugins->get('escapeValueOrGetHtml');

$site = $block->page()->site();
$siteSlug = $site->slug();

$filterLocale = (bool) $siteSetting('filter_locale_values');
$lang = $plugins->get('lang')();
$langValue = $filterLocale ? [$lang, ''] : null;

$untitled = $translate('[Untitled]');

$headingTerm = $siteSetting('browse_heading_property_term');
$bodyTerm = $siteSetting('browse_body_property_term');

$showThumbnail = in_array('thumbnail', $components);
$showHeading = in_array('resource-heading', $components);
$showBody = in_array('resource-body', $components);

// Deprecated settings are in block layout data. Furthermore, the overridden
// block allowed to use another site than the current one (useful for a main
// site and specific ones).

$pagination = (bool) $block->layoutDataValue('pagination');
$sortHeadings = $block->layoutDataValue('sort_headings', []);
?>

<div class="block preview-block">

    <?php if (!empty($heading)): ?>
    <h2><?= $escape($heading) ?></h2>
    <?php endif; ?>

    <?php // Normally not available. ?>
    <?php if (!empty($sortHeadings)): ?>
    <div class="browse-controls">
        <?= $this->sortSelector($sortHeadings) ?>
    </div>
    <?php endif; ?>

    <ul class="resource-list preview">
    <?php
    $heading = '';
    $body = '';
    foreach ($resources as $resource):
        if ($showHeading) {
            $heading = $headingTerm ? $resource->value($headingTerm, ['default' => $untitled, 'lang' => $langValue]) : $resource->displayTitle(null, $langValue);
        }
        if ($showBody) {
            $body = $bodyTerm ? $resource->value($bodyTerm, ['lang' => $langValue]) : $resource->displayDescription(null, $langValue);
        }
        $thumb = $showThumbnail ? $thumbnail($resource, 'medium', ['title' => $heading]) : null;
        ?>
        <li class="resource <?= $resourceType ?>">
            <?php if ($thumb): ?>
            <?= $resource->linkRaw($thumb) ?>
            <?php endif; ?>
            <?php if ($showHeading && $heading): ?>
            <h4><span class="resource-name"><?= $hyperlink->raw($escape($heading), null, ['class' => 'resource-link']) ?></span></h4>
            <?php endif; ?>
            <?php if ($showBody && $body): ?>
            <div class="description">
                <?= $escapeValueOrGetHtml($body) ?>
            </div>
            <?php endif; ?>
        </li>
    <?php endforeach; ?>
    </ul>

    <?php // Normally not available.
    if (!empty($pagination)):
        echo $this->pagination();
    endif;
    ?>

    <?php if ($linkText): ?>
        <?= $hyperlink($linkText, $url(
            'site/resource', ['controller' => $resourceType, 'action' => 'browse', 'site-slug' => $siteSlug], ['query' => $query], true
        )) ?>
    <?php endif; ?>

</div>
