<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SitePageBlockRepresentation $block
 * @var string $text
 * @var int $level
 */

$escape = $this->plugin('escapeHtml');
?>

        <?php if (strlen($text)): ?>
        <h<?= $level ?>><?= $escape($text) ?></h<?= $level ?>>
        <?php endif; ?>

    </div><?php // End of fake wrapper-blocks. ?>
</details>
