<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SitePageBlockRepresentation $block
 * @var string $text
 * @var int $level
 */

$escape = $this->plugin('escapeHtml');
?>

<details class="block block-heading block-heading-details">

    <summary>
        <h<?= $level ?>><?= $escape($text) ?></h<?= $level ?>>
    </summary>

    <?php // Avoid to close the current block. The block heading-details-end should be appended to reopen it, so all blocks are wrapped inside details. ?>
    <div class="wrapper-blocks">
