<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteBlockAttachmentRepresentation[] $attachments
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$thumbnail = $plugins->get('thumbnail');
$siteSetting = $plugins->get('siteSetting');

// Not managed in core template "item-with-metadata" for now.
$filterLocale = (bool) $siteSetting('filter_locale_values');
$lang = $filterLocale ? $this->lang() : null;

$options = [];
if ($siteSetting('exclude_resources_not_in_site')) {
    $options['siteId'] = $plugins->get('currentSite')()->id();
}
?>

<div class="block item-with-metadata">
<?php foreach ($attachments as $attachment): ?>
    <?php $item = $attachment->item(); ?>
    <?php if (empty($item)) continue; ?>
    <div class="resource show">
        <?= $item->displayValues($options) ?>
    <?php $itemSets = $item->itemSets(); ?>
    <?php if (count($itemSets)): ?>
        <dl class="item-sets">
            <div class="property">
                <dt><?= $translate('Item sets') ?></dt>
                <?php foreach ($itemSets as $itemSet): ?>
                <dd class="value"><?= $itemSet->link($itemSet->displayTitle(null, $lang)) ?></dd>
                <?php endforeach; ?>
            </div>
        </dl>
    <?php endif; ?>
    <?php $medias = $item->media(); ?>
    <?php if ($medias): ?>
        <dl class="media-list">
            <div class="property">
                <dt><?= $translate('Media') ?></dt>
                <?php foreach ($medias as $media): ?>
                <dd class="value"><?= $media->linkRaw($thumbnail($media, 'medium', ['title' => $media->displayTitle(null, $lang)]), null, ['class' => 'media resource']) ?></dd>
                <?php endforeach; ?>
            </div>
        </dl>
    <?php endif; ?>
    </div>
<?php endforeach; ?>
</div>
