<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SitePageBlockRepresentation $block
 * @var \Omeka\Api\Representation\SiteBlockAttachmentRepresentation[] $attachments
 * @var string $thumbnailType
 * @var string $showTitleOption "item_title" or "file_name" or "none".
 */

$plugins = $this->getHelperPluginManager();
$hyperlink = $plugins->get('hyperlink');
$siteSetting = $plugins->get('siteSetting');

$linkType = $siteSetting('attachment_link_type', 'item');

$filterLocale = (bool) $siteSetting('filter_locale_values');
$lang = $filterLocale ? $this->lang() : null;
?>

<div class="block media-text">
    <div class="<?= $thumbnailType ?> media file">
        <div class="attachments">
            <?php
            foreach ($attachments as $attachment):
                $render = null;
                $title = null;
                $link = null;
                $item = $attachment->item();
                if ($item) {
                    $media = $attachment->media() ?: $item->primaryMedia();
                    if ($media) {
                        $render = $media->render([
                            'thumbnailType' => $thumbnailType,
                            'link' => $linkType,
                        ]);
                    }

                    if ($showTitleOption == 'item_title') {
                        $title = $item->displayTitle(null, $lang);
                    } elseif ($media && $showTitleOption == 'file_name') {
                        $title = $media->displayTitle(null, $lang);
                    }

                    if ($title) {
                        if ($media && $linkType === 'media') {
                            $link = $media->link($title);
                        } elseif ($media && $linkType === 'original' && $media->hasOriginal()) {
                            $link = $hyperlink($title, $media->originalUrl());
                        } else {
                            $link = $item->link($title);
                        }
                    }
                }

                $caption = $attachment->caption();
            ?>
            <div class="item resource">
                <?= $render ?>
                <?= $link ?>
                <div class="caption">
                    <?= $caption ?>
                </div>
            </div>
            <?php endforeach; ?>
        </div>
    </div>
</div>
