<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SitePageBlockRepresentation $block
 * @var \Omeka\Api\Representation\SiteBlockAttachmentRepresentation[] $attachments
 * @var string $thumbnailType
 * @var string $link Link type from site setting "attachment_link_type"
 * @var string $showTitleOption "item_title", "file_name", "no_title"
 * @var array $classes
 * @var string $mediaDisplay "" or "thumbnail"
 */

$plugins = $this->getHelperPluginManager();
$siteLang = $plugins->get('lang')();
$hyperlink = $plugins->get('hyperlink');
$thumbnail = $plugins->get('thumbnail');
$siteSetting = $plugins->get('siteSetting');

// Not managed in core template "file" for now.
$filterLocale = (bool) $siteSetting('filter_locale_values');
$lang = $filterLocale ? $siteLang : null;
?>

<div class="block item-showcase">
    <?php
    foreach ($attachments as $attachment):
        $render = null;
        $title = null;
        $resourceLink = null;
        $item = $attachment->item();
        $media = null;
        if ($item) {
            $media = $attachment->media() ?: $item->primaryMedia();
            if ($media) {
                $render = $item->linkRaw($thumbnail($media, $thumbnailType));
            }

            if ($showTitleOption === 'item_title') {
                $title = $item->displayTitle(null, $lang);
            } elseif ($media && $showTitleOption == 'file_name') {
                $title = $media->displayTitle(null, $lang);
            }

            if ($title) {
                if ($media && $link === 'media') {
                    $resourceLink = $media->link($title);
                } elseif ($media && $link === 'original' && $media->hasOriginal()) {
                    $resourceLink = $hyperlink($title, $media->originalUrl());
                } else {
                    $resourceLink = $item->link($title);
                }
            }
        }

        $caption = $attachment->caption();
    ?>
    <div class="item resource">
        <?= $render ?>
        <?php if ($resourceLink): ?>
        <h3><?= $resourceLink ?></h3>
        <?php endif; ?>
        <?php if ($caption): ?>
        <div class="caption">
            <?= $caption ?>
        </div>
        <?php endif; ?>
    </div>
<?php endforeach; ?>
</div>
