<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 */

// A simple block to do something not possible with default blocks.

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
?>

<div class="block resource-block block-simple">
    <?= $translate('Simple block to customize in theme') ?>
</div>
