<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 * @var array $buttons
 * @var bool $displayAsButton
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$escapeAttr = $plugins->get('escapeHtmlAttr');
$htmlAttributes = $plugins->get('htmlAttributes');
?>

<div class="block resource-block block-buttons">

<?php if ($displayAsButton): $labelShare = $escapeAttr($translate('Share')); ?>
<details class="button-details buttons-details">
    <summary class="button" title="<?= $labelShare ?>" aria-label="<?= $labelShare ?>" aria-expanded="false"><span class="fas fa-share-alt"></span></summary>
<?php endif; ?>

    <?php if ($buttons): ?>
    <ul class="share-buttons">
    <?php foreach ($buttons as $button => $data): ?>
    <li>
        <?php switch ($button):
            case 'download':
            case 'print':
            case 'email':
            case 'facebook':
            case 'instagram':
            case 'linkedin':
            case 'pinterest':
            case 'twitter':
            default:
            ?>
        <a <?= empty($data['attrs']) ? '' : $htmlAttributes($data['attrs']) ?>>
            <?= $translate($data['label']) ?>
        </a>
        <?php break;
            endswitch; ?>
    </li>
    <?php endforeach; ?>
    </ul>
    <?php endif; ?>

<?php if ($displayAsButton): ?>
</details>
<?php endif; ?>

</div>
