<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 *
 * For themes:
 * @var bool $appendSite
 * @var bool $appendDate
 * @var bool $asText
 */

// Cite this document.
// Author name, title, date published, source + identifier, consulted on date.

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
$escapeAttr = $plugins->get('escapeHtmlAttr');

// Some params.
$appendSite = !empty($appendSite);
$appendDate = !empty($appendDate);
$asText = !empty($asText);

$propertyCreator = 'dcterms:creator';
$propertyPublisher = 'dcterms:publisher';
$propertyDate = 'dcterms:date';
$propertySource = 'dcterms:source';

// Format: only Chicago is managed.

$citation = '';

$creators = $resource->value($propertyCreator, ['all' => true]) ?: [];
// Strip formatting and remove empty creator elements.
$creators = array_values(array_filter(array_map('strip_tags', $creators))) ?: '';
if ($creators) {
    switch (count($creators)) {
        case 1:
            $creator = $creators[0];
            break;
        case 2:
            // Chicago-style item citation: two authors.
            $creator = sprintf($translate('%1$s and %2$s'), $creators[0], $creators[1]);
            break;
        case 3:
            // Chicago-style item citation: three authors.
            $creator = sprintf($translate('%1$s, %2$s, and %3$s'), $creators[0], $creators[1], $creators[2]);
            break;
        default:
            // Chicago-style item citation: more than three authors.
            $creator = sprintf($translate('%s et al.'), $creators[0]);
            break;
    }
    $citation .= $creator;
}

$title = $resource->displayTitle();
$citation .= ($citation ? ', ' : '') . '“' . $title . '”';

$publisher = $resource->value($propertyPublisher);
if ($publisher) {
    $citation .= ', ' . $publisher;
}

$portail = $this->setting('installation_title');
if ($portail) {
    $citation .= ', ' . $portail;
    $citation .= ' [' . $translate('online') . ']';
} else {
    $citation .= ', [' . $translate('online') . ']';
}

$date = $resource->value($propertyDate);
if ($date) {
    $citation .= ', ' . $date;
}

$sources = $resource->value($propertySource, ['all' => true]) ?: [];
// Strip formatting and remove empty elements.
$sources = array_values(array_filter(array_map('strip_tags', $sources))) ?: '';
if ($sources) {
    switch (count($sources)) {
        case 1:
            $source = $sources[0];
            break;
        case 2:
            $source = sprintf('%1$s, %2$s', $sources[0], $sources[1]);
            break;
        case 3:
        default:
            // $source = implode(', ', $sources);
            $source = sprintf('%1$s, %2$s', $sources[0], $sources[1]);
            break;
    }
    $citation .= ', ' . $source;
}

if ($appendSite) {
    $online = $escape($this->i18n()->dateFormat($resource->created(), 'medium'));
    $citation .= ', ' . sprintf($translate('put online %1$s'), $online);
}

if ($appendDate) {
    $consulted = $escape($this->i18n()->dateFormat(new \DateTime(), 'medium'));
    $citation .= '. ' . sprintf($translate('Accessed on %1$s'), $consulted);
}

$url = $resource->siteUrl(null, true);
if ($asText) {
    $citation .= ', ' . $url;
}
?>

<div class="block resource-block block-citation block-citation-resource">
    <p class="citation"><?= $escape($citation) ?><?php if (!$asText): ?>, <a class="citation-url item-info-quote-url" href="<?= $escapeAttr($url) ?>"><?= $escape($url) ?></a><?php endif; ?></p>
</div>
