<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 */

$plugins = $this->getHelperPluginManager();
$isHtml = $plugins->get('isHtml');
$escape = $plugins->get('escapeHtml');
$siteSetting = $plugins->get('siteSetting');

$filterLocale = (bool) $siteSetting('filter_locale_values');
$lang = $this->lang();
$langValue = $filterLocale ? [$lang, ''] : null;

$string = trim($resource->displayDescription(null, $langValue) ?? '');
if ($string === '') return;
?>

<div class="block-resource block-description">
    <?= $isHtml($string) ? $string : $escape($string) ?>
</div>
