<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$siteSetting = $plugins->get('siteSetting');

$filterLocale = (bool) $siteSetting('filter_locale_values');
$lang = $this->lang();
$valueLang = $filterLocale ? [$lang, ''] : null;

$value = $resource->displayDescription(null, $valueLang);
$html = is_object($value) && in_array($value->type(), ['html', 'xml']) ? $value->render() : $escape($value);
?>

<?= $html ?>
