<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 */

$primaryMedia = $resource->primaryMedia();
if (!$primaryMedia || !$primaryMedia->hasOriginal()) return;

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$escapeAttr = $plugins->get('escapeHtmlAttr');

$sizeUnit = function (int $size) use ($translate): string {
    $sizes = ['Bytes', 'kB', 'MB', 'GB', 'TB'];
    for ($i=0; $size > 1000 && $i < count($sizes) - 1; $i++) $size /= 1000;
    return sprintf('%1$s %2$s', number_format($size, 0, ',', ' '), $translate($sizes[$i]));
};

$size = (int) $primaryMedia->size();
$title = sprintf($translate('Download file (%s)'), $sizeUnit($size));
?>

<a class="button link-original download-file" title="<?= $escapeAttr($title) ?>" aria-label="<?= $escapeAttr($title) ?>" href="<?= $escapeAttr($primaryMedia->originalUrl()) ?>" download="<?= $escapeAttr(basename($primaryMedia->source())) ?>" target="_self">
    <span class="button-download o-icon- fa fa-download"></span>
</a>
