<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\MediaRepresentation $resource
 * @var \Omeka\Api\Representation\ItemRepresentation $item
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$siteSetting = $plugins->get('siteSetting');

$filterLocale = (bool) $siteSetting('filter_locale_values');
$lang = $this->lang();
$langValue = $filterLocale ? [$lang, ''] : null;
?>

<div class="block block-resource block-media-part-of-item">
    <p class="media-parent-item">
        <?= sprintf($translate('Part of %s'), $item->link($item->displayTitle(null, $langValue))) ?>
    </p>
</div>
