<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $previous
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $next
 * @var bool $back
 * @var string $lastBrowseUrl
 * @var array $options Passed options.
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');
?>

<div class="block resource-block block-previous-next">
    <?php if ($previous): ?>
        <?= $hyperlink('<', $previous->siteUrl(), ['class' => 'button', 'rel' => 'prev', 'title' => $translate('Previous resource')]) ?>
    <?php else: ?>
        <?= $hyperlink('<', '#', ['class' => 'button', 'rel' => 'prev', 'title' => $translate('No previous resource'), 'disabled' => 'disabled', 'style' => 'color:gray;pointer-events:none;', 'tabindex' => '-1']) ?>
    <?php endif; ?>
    <?php /* // Not configurable in resource page block.
    <?php if (!empty($back): ?>
        <?php if ($lastBrowseUrl): ?>
            <?= $hyperlink('^', $lastBrowseUrl, ['class' => 'button', 'rel' => 'search', 'title' => $translate('Back to last search')]) ?>
        <?php else: ?>
            <?= $hyperlink('^', '#', ['class' => 'button', 'rel' => 'search', 'title' => $translate('Back to last search'), 'disabled' => 'disabled', 'style' => 'color:gray;pointer-events:none;', 'tabindex' => '-1']) ?>
        <?php endif; ?>
    <?php endif; ?>
    */ ?>
    <?php if ($next): ?>
        <?= $hyperlink('>', $next->siteUrl(), ['class' => 'button', 'rel' => 'next', 'title' => $translate('Next resource')]) ?>
    <?php else: ?>
        <?= $hyperlink('>', '#', ['class' => 'button', 'rel' => 'next', 'title' => $translate('No next resource'), 'disabled' => 'disabled', 'style' => 'color:gray;pointer-events:none;', 'tabindex' => '-1']) ?>
    <?php endif; ?>
</div>
