<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
$easyMeta = $plugins->get('easyMeta');
$escapeAttr = $plugins->get('escapeHtmlAttr');

$resourceType = $resource->getControllerName();
?>

<div class="block resource-block block-resource-type">
    <div class="resource-type <?= $escapeAttr($resourceType) ?>"><?= $escape($translate(ucfirst($easyMeta->resourceLabel($resourceType)))) ?></div>
</div>
