<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$easyMeta = $plugins->get('easyMeta');
?>

<div class="resource-type <?= $resource->getControllerName() ?>"><?= $translate(ucfirst($easyMeta->resourceLabel($resource))) ?></div>
