<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$easyMeta = $plugins->get('easyMeta');

$resourceType = $resource->getControllerName();
?>

<div class="block resource-block block-resource-type">
    <div class="resource-type <?= $resourceType ?>"><?= $translate(ucfirst($easyMeta->resourceLabel($resourceType))) ?></div>
</div>
