<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation[] $relatedResources
 * @var string $resourceType
 * @var string $heading
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
$thumbnail = $plugins->get('thumbnail');
?>

<div class="block resource-block block-see-also preview-block<?= empty($relatedResources) ? ' no-resources' : '' ?>">

    <?php if (!empty($heading)): ?>
    <h2><?= $escape($translate($heading)) ?></h2>
    <?php endif; ?>

    <?php if (empty($relatedResources)): ?>
    <p><?= $translate('No related resources.') ?></p>
    <?php else: ?>
    <ul class="see-also-resources resource-list preview">
    <?php foreach ($relatedResources as $relatedResource):
        $linkContent = '';
        $thumb = $relatedResource->primaryMedia();
        if ($thumb) {
            $linkContent .= $thumbnail($thumb, 'medium');
        }
        $linkContent .= '<span class="resource-name">' . $escape($relatedResource->displayTitle()) . '</span>';
        ?>
        <li class="<?= $escape($relatedResource->resourceName()) ?> resource see-also-resource">
            <?= $relatedResource->linkRaw($linkContent, null, ['class' => 'resource-link']) ?>
        </li>
    <?php endforeach; ?>
    </ul>
    <?php endif; ?>

</div>
