<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation[] $similarResources
 * @var string $resourceType
 * @var string $heading
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
$thumbnail = $plugins->get('thumbnail');
?>

<div class="block resource-block block-similar-content preview-block<?= empty($similarResources) ? ' no-resources' : '' ?>">

    <?php if (!empty($heading)): ?>
    <h2><?= $escape($translate($heading)) ?></h2>
    <?php endif; ?>

    <?php if (empty($similarResources)): ?>
    <p><?= $translate('No similar resources.') ?></p>
    <?php else: ?>
    <ul class="similar-content-resources resource-list preview">
    <?php foreach ($similarResources as $similarResource):
        $linkContent = '';
        $thumb = $similarResource->primaryMedia();
        if ($thumb) {
            $linkContent .= $thumbnail($thumb, 'medium');
        }
        $linkContent .= '<span class="resource-name">' . $escape($similarResource->displayTitle()) . '</span>';
        ?>
        <li class="<?= $escape($similarResource->resourceName()) ?> resource similar-content-resource">
            <?= $similarResource->linkRaw($linkContent, null, ['class' => 'resource-link']); ?>
        </li>
    <?php endforeach; ?>
    </ul>
    <?php endif; ?>

</div>
